services:
  db:
    image: "postgres:alpine"
    ports:
      - 5432:5432
    env_file: ".env"
    volumes:
      - ./dataset/csv_files:/var/lib/postgresql/csv_files
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
  db_api:
    depends_on:
      - db
    image: "postgrest/postgrest"
    ports:
      - 3000:3000
    env_file: ".env"
  swagger-ui:
    image: "swaggerapi/swagger-ui"
    depends_on:
      - db_api
    ports:
      - "8080:8080"
    expose:
      - "8080"
    env_file: ".env"
