services:
  db:
    image: "postgres:alpine"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "example"
    volumes:
      - ./dataset/csv_files:/var/lib/postgresql/csv_files
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
  db_api:
    depends_on:
      - db
    image: "postgrest/postgrest"
    ports:
      - 3000:3000
    environment:
      PGRST_DB_URI: postgres://authenticator:mysecretpassword@db:5432/postgres
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
      PGRST_DB_ANON_ROLE: "web_anon"
      PGRST_DB_SCHEMAS: "api"
  swagger-ui:
    image: "swaggerapi/swagger-ui"
    depends_on:
      - db_api
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://127.0.0.1:3000/
